### ISSUE TITLE
Adding EntityDef to a struct makes elided lifetimes fail

### ISSUE THREAD

**Issue by TheDanBlanco** [neoeinstein/modyne#18]
given the following struct

```
pub struct Key<'a> {
    material: &'a str,
}
```

adding the `EntityDef` trait makes the struct fail to compile with the warning:

```
implicit elided lifetime not allowed here
expected lifetime parameter
```

in this case, it's easily worked around by using a string, but i thought i'd bring it to your attention. i didn't see anywhere in the docs that this would be something to look out for.

**Comment by neoeinstein** [comment]
The derive macro could potentially be expanded to support generic struct entities, but you're right that it does not as of now. You could try a manual implementation of the `EntityDef` trait to see if you can make that work. However, because of the fact that the underlying AWS SDK relies on owned values for reading and writing, there isn't much to be gained in terms of entities that borrow their values.

This will become more apparent on the deserialization side, as there isn't an external owned value that can easily act as the bound for a borrowed projection, and you'll get a runtime serde error attempting to borrow the value out of consumed `Item` (`invalid type: string "<string-in-item>", expected a borrowed string`). It is possible to manually create a borrowed `Entity` with an owned `Projection` for reading, but I think this is a use case that is easier to get wrong than to get right.
